cluster:
  # 2 workers in dev mode. It should be enough.
  workers: 2

cookies:
  prefix: 'bop_dev'

database:
  # Supported types: mariadb and mysql
  dbname: 'bop_dev'
  username: 'bop_dev'
  password: 'bop'
  log: true

log:
  level: debug
  console:
    enabled: true
  syslog:
    enabled: false

redis:
  prefix: bop_dev

server:
  hostname: localhost
  port: 12340
  https: false

notifier:
  hostname: localhost
  port: 12341
  https: false
  adminui: false
